import { OCTET_STREAM } from './mime';

/**
 * Response headers for `GET /api/files/[id]`: the XSS boundary for every stored
 * file.
 *
 * `Attachment.mimeType` is NOT trusted here. For inbound email it was the
 * sender's own `Content-Type` until ingest started sniffing bytes, and old rows
 * still carry whatever the sender claimed (`text/html`, `image/svg+xml`, ...).
 * Deciding at read time is what neutralizes those rows without a migration.
 *
 * NOTE: a header of the same name set in `next.config.ts` `headers()` REPLACES
 * the one set here. Next writes config headers first and then skips any
 * route-handler header that is already present
 * (node_modules/next/dist/server/send-response.js). Keep global CSP / framing
 * headers scoped away from /api/files/.
 */

/**
 * Types a browser may RENDER in our origin. Each is a raster image or a PDF:
 * formats that run no script in the page's origin. Everything else a sender
 * can name (SVG, HTML, XML, JS, ...) is served as a download. This is an
 * allow-list and must stay one.
 *
 * Deliberately separate from ALLOWED_MIME (what uploads accept), even though
 * the two match today: widening uploads must not silently widen what renders.
 */
const INLINE_SAFE_MIME: ReadonlySet<string> = new Set([
  'image/jpeg',
  'image/png',
  'image/webp',
  'image/heic',
  'application/pdf',
]);

/**
 * `sandbox` gives the document a unique opaque origin with scripts, forms and
 * plugins disabled, so even a file a browser chooses to render can't act as the
 * signed-in user. `default-src 'none'` stops it loading anything. The
 * `style-src 'unsafe-inline'` is for the synthetic wrapper page browsers build
 * around a top-level image or PDF.
 *
 * This exact policy is the one Redmine serves attachments with. Chrome and
 * Firefox render PDFs under it (both exempt their built-in viewer from page CSP:
 * Chromium issue 40328564, Mozilla bug 1582115). Safari does from 18.4 (Redmine
 * #40647). Safari <= 18.3 shows such a PDF blank, which is the accepted cost.
 */
const FILE_CSP = "default-src 'none'; style-src 'unsafe-inline'; sandbox";

function normalizeMime(mimeType: string | null): string {
  return (mimeType ?? '').split(';')[0].trim().toLowerCase();
}

/**
 * RFC 6266: a quoted ASCII fallback for old clients, then the exact UTF-8 name
 * in `filename*`. The fallback replaces anything outside printable ASCII
 * (including CR/LF), plus `"` and `\` (which would break the quoted string) and
 * `%` (which some clients percent-decode inside it).
 */
function contentDisposition(kind: 'inline' | 'attachment', filename: string | null): string {
  const name = filename?.trim() ? filename : 'download';
  const fallback = name.replace(/[^\x20-\x7e]|["\\%]/g, '_');
  const encoded = encodeURIComponent(name).replace(
    /['()*]/g,
    (c) => `%${c.charCodeAt(0).toString(16).toUpperCase()}`,
  );
  return `${kind}; filename="${fallback}"; filename*=UTF-8''${encoded}`;
}

export function fileResponseHeaders(input: {
  mimeType: string | null;
  filename: string | null;
  isThumbnail: boolean;
  size: number;
}): Headers {
  let renderable: string | null = null;
  if (input.isThumbnail) {
    // Thumbnails are generated by our worker (sharp -> webp), not sender bytes.
    renderable = 'image/webp';
  } else {
    const stored = normalizeMime(input.mimeType);
    if (INLINE_SAFE_MIME.has(stored)) renderable = stored;
  }

  const headers = new Headers();
  headers.set('Content-Type', renderable ?? OCTET_STREAM);
  headers.set('Content-Length', String(input.size));
  headers.set(
    'Content-Disposition',
    contentDisposition(renderable ? 'inline' : 'attachment', input.filename),
  );
  headers.set('X-Content-Type-Options', 'nosniff');
  headers.set('Content-Security-Policy', FILE_CSP);
  headers.set('Cache-Control', 'private, max-age=300');
  return headers;
}
